// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOC2M7PP2MXRUlWoBqKTi_Kt5vFlwG94Q',
    appId: '1:192770331762:web:ef0c628a0db8c3e7631eeb',
    messagingSenderId: '192770331762',
    projectId: 'pokedexflutterapp',
    authDomain: 'pokedexflutterapp.firebaseapp.com',
    storageBucket: 'pokedexflutterapp.firebasestorage.app',
    measurementId: 'G-TPWSN9QS0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYtSGoCvxWIr6kORiSdyOZ3bsm36_XKro',
    appId: '1:192770331762:android:716d720536cbc274631eeb',
    messagingSenderId: '192770331762',
    projectId: 'pokedexflutterapp',
    storageBucket: 'pokedexflutterapp.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOC2M7PP2MXRUlWoBqKTi_Kt5vFlwG94Q',
    appId: '1:192770331762:web:b99d40d669a3fa79631eeb',
    messagingSenderId: '192770331762',
    projectId: 'pokedexflutterapp',
    authDomain: 'pokedexflutterapp.firebaseapp.com',
    storageBucket: 'pokedexflutterapp.firebasestorage.app',
    measurementId: 'G-LENCEC25Q4',
  );

}